### ISSUE TITLE
The example code falis to build with errors

### ISSUE THREAD

**Issue by koder77** [jackbergus/mpreal#1]
[stefan@tuxmobile example]$ make
g++ -c example.cpp
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h: In Kopierkonstruktor »mpfr::mpreal::mpreal(const mpfr::mpreal&)«:
../mpreal.h:610:27: Fehler: keine passende Funktion für Aufruf von »mpfr::mpreal::mpfr_srcptr(mpfr_srcptr)«
  610 |     mpfr_init2(mpfr_ptr(),mpfr_get_prec(u.mpfr_srcptr()));
      |                           ^~~~~~~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:324:19: Anmerkung: Kandidat: »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
  324 |     ::mpfr_srcptr mpfr_srcptr() const;
      |                   ^~~~~~~~~~~
../mpreal.h:324:19: Anmerkung:   Kandidat erwartet 0 Argumente, 1 angegeben
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h:610:27: Fehler: keine passende Funktion für Aufruf von »mpfr::mpreal::mpfr_srcptr(mpfr_srcptr)«
  610 |     mpfr_init2(mpfr_ptr(),mpfr_get_prec(u.mpfr_srcptr()));
      |                           ^~~~~~~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:324:19: Anmerkung: Kandidat: »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
  324 |     ::mpfr_srcptr mpfr_srcptr() const;
      |                   ^~~~~~~~~~~
../mpreal.h:324:19: Anmerkung:   Kandidat erwartet 0 Argumente, 1 angegeben
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h:611:5: Fehler: expected »;« before »_p«
  611 |     mpfr_set  (mpfr_ptr(),u.mpfr_srcptr(),mpreal::get_default_rnd());
      |     ^~~~~~~~
../mpreal.h:611:5: Fehler: ungültige Verwendung der nicht-statischen Elementfunktion »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
  611 |     mpfr_set  (mpfr_ptr(),u.mpfr_srcptr(),mpreal::get_default_rnd());
      |     ^~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:324:19: Anmerkung: hier deklariert
  324 |     ::mpfr_srcptr mpfr_srcptr() const;
      |                   ^~~~~~~~~~~
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h:611:5: Fehler: »_p« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »mp«?
  611 |     mpfr_set  (mpfr_ptr(),u.mpfr_srcptr(),mpreal::get_default_rnd());
      |     ^~~~~~~~
../mpreal.h: In Konstruktor »mpfr::mpreal::mpreal(const __mpfr_struct*, bool)«:
../mpreal.h:644:32: Fehler: keine passende Funktion für Aufruf von »mpfr::mpreal::mpfr_srcptr(const __mpfr_struct*&)«
  644 |         mpfr_init2(mpfr_ptr(), mpfr_get_prec(u));
      |                                ^~~~~~~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:324:19: Anmerkung: Kandidat: »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
  324 |     ::mpfr_srcptr mpfr_srcptr() const;
      |                   ^~~~~~~~~~~
../mpreal.h:324:19: Anmerkung:   Kandidat erwartet 0 Argumente, 1 angegeben
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h:644:32: Fehler: keine passende Funktion für Aufruf von »mpfr::mpreal::mpfr_srcptr(const __mpfr_struct*&)«
  644 |         mpfr_init2(mpfr_ptr(), mpfr_get_prec(u));
      |                                ^~~~~~~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:324:19: Anmerkung: Kandidat: »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
  324 |     ::mpfr_srcptr mpfr_srcptr() const;
      |                   ^~~~~~~~~~~
../mpreal.h:324:19: Anmerkung:   Kandidat erwartet 0 Argumente, 1 angegeben
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h:645:9: Fehler: expected »;« before »_p«
  645 |         mpfr_set  (mpfr_ptr(), u, mpreal::get_default_rnd());
      |         ^~~~~~~~
../mpreal.h:645:9: Fehler: ungültige Verwendung der nicht-statischen Elementfunktion »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
  645 |         mpfr_set  (mpfr_ptr(), u, mpreal::get_default_rnd());
      |         ^~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:324:19: Anmerkung: hier deklariert
  324 |     ::mpfr_srcptr mpfr_srcptr() const;
      |                   ^~~~~~~~~~~
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h:645:9: Fehler: »_p« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »mp«?
  645 |         mpfr_set  (mpfr_ptr(), u, mpreal::get_default_rnd());
      |         ^~~~~~~~
../mpreal.h: In Elementfunktion »mpfr::mpreal& mpfr::mpreal::operator=(const mpfr::mpreal&)«:
../mpreal.h:949:24: Fehler: keine passende Funktion für Aufruf von »mpfr::mpreal::mpfr_srcptr(mpfr_srcptr)«
  949 |         mp_prec_t tp = mpfr_get_prec(  mpfr_srcptr());
      |                        ^~~~~~~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:324:19: Anmerkung: Kandidat: »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
  324 |     ::mpfr_srcptr mpfr_srcptr() const;
      |                   ^~~~~~~~~~~
../mpreal.h:324:19: Anmerkung:   Kandidat erwartet 0 Argumente, 1 angegeben
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h:949:24: Fehler: keine passende Funktion für Aufruf von »mpfr::mpreal::mpfr_srcptr(mpfr_srcptr)«
  949 |         mp_prec_t tp = mpfr_get_prec(  mpfr_srcptr());
      |                        ^~~~~~~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:324:19: Anmerkung: Kandidat: »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
  324 |     ::mpfr_srcptr mpfr_srcptr() const;
      |                   ^~~~~~~~~~~
../mpreal.h:324:19: Anmerkung:   Kandidat erwartet 0 Argumente, 1 angegeben
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h:950:24: Fehler: keine passende Funktion für Aufruf von »mpfr::mpreal::mpfr_srcptr(mpfr_srcptr)«
  950 |         mp_prec_t vp = mpfr_get_prec(v.mpfr_srcptr());
      |                        ^~~~~~~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:324:19: Anmerkung: Kandidat: »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
  324 |     ::mpfr_srcptr mpfr_srcptr() const;
      |                   ^~~~~~~~~~~
../mpreal.h:324:19: Anmerkung:   Kandidat erwartet 0 Argumente, 1 angegeben
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h:950:24: Fehler: keine passende Funktion für Aufruf von »mpfr::mpreal::mpfr_srcptr(mpfr_srcptr)«
  950 |         mp_prec_t vp = mpfr_get_prec(v.mpfr_srcptr());
      |                        ^~~~~~~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:324:19: Anmerkung: Kandidat: »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
  324 |     ::mpfr_srcptr mpfr_srcptr() const;
      |                   ^~~~~~~~~~~
../mpreal.h:324:19: Anmerkung:   Kandidat erwartet 0 Argumente, 1 angegeben
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h:957:9: Fehler: expected »;« before »_p«
  957 |         mpfr_set(mpfr_ptr(), v.mpfr_srcptr(), mpreal::get_default_rnd());
      |         ^~~~~~~~
../mpreal.h:957:9: Fehler: ungültige Verwendung der nicht-statischen Elementfunktion »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
  957 |         mpfr_set(mpfr_ptr(), v.mpfr_srcptr(), mpreal::get_default_rnd());
      |         ^~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:324:19: Anmerkung: hier deklariert
  324 |     ::mpfr_srcptr mpfr_srcptr() const;
      |                   ^~~~~~~~~~~
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h:957:9: Fehler: »_p« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »mp«?
  957 |         mpfr_set(mpfr_ptr(), v.mpfr_srcptr(), mpreal::get_default_rnd());
      |         ^~~~~~~~
../mpreal.h: In Elementfunktion »mpfr::mpreal& mpfr::mpreal::operator=(const char*)«:
../mpreal.h:1071:19: Fehler: keine passende Funktion für Aufruf von »mpfr::mpreal::mpfr_srcptr(mpfr_srcptr)«
 1071 |     mpfr_init2(t, mpfr_get_prec(mpfr_srcptr()));
      |                   ^~~~~~~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:324:19: Anmerkung: Kandidat: »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
  324 |     ::mpfr_srcptr mpfr_srcptr() const;
      |                   ^~~~~~~~~~~
../mpreal.h:324:19: Anmerkung:   Kandidat erwartet 0 Argumente, 1 angegeben
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h:1071:19: Fehler: keine passende Funktion für Aufruf von »mpfr::mpreal::mpfr_srcptr(mpfr_srcptr)«
 1071 |     mpfr_init2(t, mpfr_get_prec(mpfr_srcptr()));
      |                   ^~~~~~~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:324:19: Anmerkung: Kandidat: »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
  324 |     ::mpfr_srcptr mpfr_srcptr() const;
      |                   ^~~~~~~~~~~
../mpreal.h:324:19: Anmerkung:   Kandidat erwartet 0 Argumente, 1 angegeben
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h:1075:9: Fehler: expected »;« before »_p«
 1075 |         mpfr_set(mpfr_ptr(), t, mpreal::get_default_rnd());
      |         ^~~~~~~~
../mpreal.h:1075:9: Fehler: ungültige Verwendung der nicht-statischen Elementfunktion »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
 1075 |         mpfr_set(mpfr_ptr(), t, mpreal::get_default_rnd());
      |         ^~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:324:19: Anmerkung: hier deklariert
  324 |     ::mpfr_srcptr mpfr_srcptr() const;
      |                   ^~~~~~~~~~~
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h:1075:9: Fehler: »_p« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »mp«?
 1075 |         mpfr_set(mpfr_ptr(), t, mpreal::get_default_rnd());
      |         ^~~~~~~~
../mpreal.h: In Elementfunktion »mpfr::mpreal& mpfr::mpreal::operator=(const string&)«:
../mpreal.h:1094:19: Fehler: keine passende Funktion für Aufruf von »mpfr::mpreal::mpfr_srcptr(mpfr_srcptr)«
 1094 |     mpfr_init2(t, mpfr_get_prec(mpfr_srcptr()));
      |                   ^~~~~~~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:324:19: Anmerkung: Kandidat: »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
  324 |     ::mpfr_srcptr mpfr_srcptr() const;
      |                   ^~~~~~~~~~~
../mpreal.h:324:19: Anmerkung:   Kandidat erwartet 0 Argumente, 1 angegeben
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h:1094:19: Fehler: keine passende Funktion für Aufruf von »mpfr::mpreal::mpfr_srcptr(mpfr_srcptr)«
 1094 |     mpfr_init2(t, mpfr_get_prec(mpfr_srcptr()));
      |                   ^~~~~~~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:324:19: Anmerkung: Kandidat: »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
  324 |     ::mpfr_srcptr mpfr_srcptr() const;
      |                   ^~~~~~~~~~~
../mpreal.h:324:19: Anmerkung:   Kandidat erwartet 0 Argumente, 1 angegeben
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h:1098:9: Fehler: expected »;« before »_p«
 1098 |         mpfr_set(mpfr_ptr(), t, mpreal::get_default_rnd());
      |         ^~~~~~~~
../mpreal.h:1098:9: Fehler: ungültige Verwendung der nicht-statischen Elementfunktion »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
 1098 |         mpfr_set(mpfr_ptr(), t, mpreal::get_default_rnd());
      |         ^~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:324:19: Anmerkung: hier deklariert
  324 |     ::mpfr_srcptr mpfr_srcptr() const;
      |                   ^~~~~~~~~~~
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h:1098:9: Fehler: »_p« wurde in diesem Gültigkeitsbereich nicht deklariert; meinten Sie »mp«?
 1098 |         mpfr_set(mpfr_ptr(), t, mpreal::get_default_rnd());
      |         ^~~~~~~~
../mpreal.h: In Elementfunktion »bool mpfr::mpreal::toBool() const«:
../mpreal.h:1750:83: Fehler: keine passende Funktion für Aufruf von »mpfr::mpreal::mpfr_srcptr(mpfr_srcptr) const«
 1750 | inline bool               mpreal::toBool   (             )  const    {    return  mpfr_zero_p (mpfr_srcptr()) == 0;     }
      |                                                                                   ^~~~~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:324:19: Anmerkung: Kandidat: »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
  324 |     ::mpfr_srcptr mpfr_srcptr() const;
      |                   ^~~~~~~~~~~
../mpreal.h:324:19: Anmerkung:   Kandidat erwartet 0 Argumente, 1 angegeben
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h: In Elementfunktion »std::string mpfr::mpreal::toString(int, int, mpfr_rnd_t) const«:
../mpreal.h:1803:49: Fehler: keine passende Funktion für Aufruf von »mpfr::mpreal::mpfr_srcptr(mpfr_srcptr) const«
 1803 |     int digits = (n >= 0) ? n : 2 + bits2digits(mpfr_get_prec(mpfr_srcptr()));
      |                                                 ^~~~~~~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:1761:23: Anmerkung: Kandidat: »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
 1761 | inline ::mpfr_srcptr  mpreal::mpfr_srcptr() const    { return mp; }
      |                       ^~~~~~
../mpreal.h:1761:23: Anmerkung:   Kandidat erwartet 0 Argumente, 1 angegeben
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h:1803:49: Fehler: keine passende Funktion für Aufruf von »mpfr::mpreal::mpfr_srcptr(mpfr_srcptr) const«
 1803 |     int digits = (n >= 0) ? n : 2 + bits2digits(mpfr_get_prec(mpfr_srcptr()));
      |                                                 ^~~~~~~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:1761:23: Anmerkung: Kandidat: »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
 1761 | inline ::mpfr_srcptr  mpreal::mpfr_srcptr() const    { return mp; }
      |                       ^~~~~~
../mpreal.h:1761:23: Anmerkung:   Kandidat erwartet 0 Argumente, 1 angegeben
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h: In Elementfunktion »int mpfr::mpreal::getPrecision() const«:
../mpreal.h:1981:16: Fehler: keine passende Funktion für Aufruf von »mpfr::mpreal::mpfr_srcptr(mpfr_srcptr) const«
 1981 |     return int(mpfr_get_prec(mpfr_srcptr()));
      |                ^~~~~~~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:1761:23: Anmerkung: Kandidat: »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
 1761 | inline ::mpfr_srcptr  mpreal::mpfr_srcptr() const    { return mp; }
      |                       ^~~~~~
../mpreal.h:1761:23: Anmerkung:   Kandidat erwartet 0 Argumente, 1 angegeben
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h:1981:16: Fehler: keine passende Funktion für Aufruf von »mpfr::mpreal::mpfr_srcptr(mpfr_srcptr) const«
 1981 |     return int(mpfr_get_prec(mpfr_srcptr()));
      |                ^~~~~~~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:1761:23: Anmerkung: Kandidat: »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
 1761 | inline ::mpfr_srcptr  mpreal::mpfr_srcptr() const    { return mp; }
      |                       ^~~~~~
../mpreal.h:1761:23: Anmerkung:   Kandidat erwartet 0 Argumente, 1 angegeben
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h: In Elementfunktion »mpfr_prec_t mpfr::mpreal::get_prec() const«:
../mpreal.h:2020:12: Fehler: keine passende Funktion für Aufruf von »mpfr::mpreal::mpfr_srcptr(mpfr_srcptr) const«
 2020 |     return mpfr_get_prec(mpfr_srcptr());
      |            ^~~~~~~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:1761:23: Anmerkung: Kandidat: »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
 1761 | inline ::mpfr_srcptr  mpreal::mpfr_srcptr() const    { return mp; }
      |                       ^~~~~~
../mpreal.h:1761:23: Anmerkung:   Kandidat erwartet 0 Argumente, 1 angegeben
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h:2020:12: Fehler: keine passende Funktion für Aufruf von »mpfr::mpreal::mpfr_srcptr(mpfr_srcptr) const«
 2020 |     return mpfr_get_prec(mpfr_srcptr());
      |            ^~~~~~~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:1761:23: Anmerkung: Kandidat: »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
 1761 | inline ::mpfr_srcptr  mpreal::mpfr_srcptr() const    { return mp; }
      |                       ^~~~~~
../mpreal.h:1761:23: Anmerkung:   Kandidat erwartet 0 Argumente, 1 angegeben
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h: In Elementfunktion »mp_exp_t mpfr::mpreal::get_exp() const«:
../mpreal.h:2031:12: Fehler: keine passende Funktion für Aufruf von »mpfr::mpreal::mpfr_srcptr(mpfr_srcptr) const«
 2031 |     return mpfr_get_exp(mpfr_srcptr());
      |            ^~~~~~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:1761:23: Anmerkung: Kandidat: »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
 1761 | inline ::mpfr_srcptr  mpreal::mpfr_srcptr() const    { return mp; }
      |                       ^~~~~~
../mpreal.h:1761:23: Anmerkung:   Kandidat erwartet 0 Argumente, 1 angegeben
In Datei, eingebunden von ../mpreal.h:125,
                 von example.cpp:50:
../mpreal.h:2031:12: Fehler: keine passende Funktion für Aufruf von »mpfr::mpreal::mpfr_srcptr(mpfr_srcptr) const«
 2031 |     return mpfr_get_exp(mpfr_srcptr());
      |            ^~~~~~~~~~~~
In Datei, eingebunden von example.cpp:50:
../mpreal.h:1761:23: Anmerkung: Kandidat: »const __mpfr_struct* mpfr::mpreal::mpfr_srcptr() const«
 1761 | inline ::mpfr_srcptr  mpreal::mpfr_srcptr() const    { return mp; }
      |                       ^~~~~~
../mpreal.h:1761:23: Anmerkung:   Kandidat erwartet 0 Argumente, 1 angegeben
make: *** [makefile:5: example.o] Fehler 1
[stefan@tuxmobile example]$ 
// ========================== end ======================================================
How can this be fixed?

**Comment by jackbergus** [comment]
Hello,

I'm sorry, but I am unable to replicate your issue. I'm providing here the specs of the OS and of the compiler that I've been using on my local machine, as I sense that the problem might be an old version of your g++ compiler:

```$ g++ --version```

```
g++ (Ubuntu 10.2.0-13ubuntu1) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I've been trying both with the CMake and by running the original Makefile, but both scenarios seems to work fine. In fact, mpfr_srcptr()  is indeed declared in line 1761, and the issue is that the structure mpfr_srcptr is a renaming for a data structure in mpfr.h, that is:

Line 252:
```
typedef const __mpfr_struct *mpfr_srcptr;
```

Where such data structure is a simple C structure defined as follows:

Line 224:
```
typedef struct {
  mpfr_prec_t  _mpfr_prec;
  mpfr_sign_t  _mpfr_sign;
  mpfr_exp_t   _mpfr_exp;
  mp_limb_t   *_mpfr_d;
} __mpfr_struct;
```

So, I sense that the problem is that the compiler does not generate the default copy/move constructor for __mpfr_struct which, in newer versions of C++, is implicitely defined, while previously you had to explicitely declare it. I also tried to do some Continuous Integration with Travis CI and Ubuntu Focal Fossa, and [all went fine](https://github.com/jackbergus/mpreal/runs/2758311531).

Please let me know if you have some other related problems, otherwise I'm going to close the issue.
